config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # list all pets
  get 'pets', to: 'pets#index'
  # create a pet
  post 'pets', to: 'pets#create'
  get 'pets/new', to: 'pets#new', as: :new_pet
  # list one pet
  get 'pets/:id', to: 'pets#show', as: :pet
  # update a pet
  get 'pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch 'pets/:id', to: 'pets#update'
  # delete a pet
  delete 'pets/:id', to: 'pets#destroy'
  # resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :found_on, presence: true
  validates :species, inclusion: { in: %w[dog cat horse mouse parrot turtle] }
  SPECIES = %w[dog cat horse mouse parrot turtle]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pets_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit; end

  def update
    @pet.update(pets_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def find_pet
    @pet = Pet.find(params[:id])
  end

  def pets_params
    params.require(:pet).permit(:name, :address, :found_on, :species)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_pet_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :content %>
  <%= f.input :species, as: :select, collection: Pet::SPECIES %>
  <%= f.input :found %>
  <%= f.input :found_on %>
  <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<%= render 'pet_form', pet: @pet %>

app/views/pets/index.html.erb
<div class="container">
  <h1>All pets</h1>
  <%= link_to 'New pet', new_pet_path %>
  <% @pets.each do |pet| %>
    <%= link_to pet_path(pet) do %>
      <h3><%= pet.name %> - <%= pet.species %></h3>
    <% end %>
    <p><%= pet.address %> found on <%= pet.found_on %></p>
  <% end  %>

</div>

app/views/pets/new.html.erb
<%= render 'pet_form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h3><%= @pet.name %> - <%= @pet.species %></h3>
<p><%= @pet.address %> found on <%= @pet.found_on %></p>
<%= link_to 'Back', pets_path %>
<%= link_to 'Edit', edit_pet_path(@pet) %>
<%= link_to 'Delete', pet_path(@pet), method: :delete %>